// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfE5uLlBsN_YCQ8MKQYvxTjYwp_8S5WQc',
    appId: '1:573859660614:web:45e482c9624063cbdcdb47',
    messagingSenderId: '573859660614',
    projectId: 'task-quest-bed42',
    authDomain: 'task-quest-bed42.firebaseapp.com',
    storageBucket: 'task-quest-bed42.firebasestorage.app',
    measurementId: 'G-8MQ6V6Y58B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLscgbzcwOr0KRNxI7HPt4BlAtRk7goNA',
    appId: '1:573859660614:android:5a2c514fe86d63ebdcdb47',
    messagingSenderId: '573859660614',
    projectId: 'task-quest-bed42',
    storageBucket: 'task-quest-bed42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ0M_kGj2xDROqW5E5iVvaDGwUe_iitf0',
    appId: '1:573859660614:ios:c4f0c68d4142c152dcdb47',
    messagingSenderId: '573859660614',
    projectId: 'task-quest-bed42',
    storageBucket: 'task-quest-bed42.firebasestorage.app',
    iosBundleId: 'com.example.taskquest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ0M_kGj2xDROqW5E5iVvaDGwUe_iitf0',
    appId: '1:573859660614:ios:c4f0c68d4142c152dcdb47',
    messagingSenderId: '573859660614',
    projectId: 'task-quest-bed42',
    storageBucket: 'task-quest-bed42.firebasestorage.app',
    iosBundleId: 'com.example.taskquest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfE5uLlBsN_YCQ8MKQYvxTjYwp_8S5WQc',
    appId: '1:573859660614:web:22e8729905ddfd3edcdb47',
    messagingSenderId: '573859660614',
    projectId: 'task-quest-bed42',
    authDomain: 'task-quest-bed42.firebaseapp.com',
    storageBucket: 'task-quest-bed42.firebasestorage.app',
    measurementId: 'G-H2LRLQ67E5',
  );
}
